const subcats = {
    "26": ["Current Events American", "Current Events Other"],
    "21": ["Fine Arts American", "Fine Arts Audiovisual", "Fine Arts Auditory", "Fine Arts British", "Fine Arts European", "Fine Arts Opera", "Fine Arts Other", "Fine Arts Visual", "Fine Arts World"],
    "20": ["Geography American", "Geography World"],
    "18": ["History American", "History British", "History Classical", "History European", "History Other", "History World"],
    "15": ["Literature American", "Literature British", "Literature Classical", "Literature European", "Literature Other", "Literature World"],
    "14": ["Mythology American", "Mythology Chinese", "Mythology Egyptian", "Mythology Greco-Roman", "Mythology Indian", "Mythology Japanese", "Mythology Norse", "Mythology Other", "Mythology Other East Asian"],
    "25": ["Philosophy American", "Philosophy Classical", "Philosophy East Asian", "Philosophy European", "Philosophy Other"],
    "19": ["Religion American", "Religion Christianity", "Religion East Asian", "Religion Islam", "Religion Judaism", "Religion Other"],
    "17": ["Science American", "Science Biology", "Science Chemistry", "Science Computer Science", "Science Math", "Science Other", "Science Physics", "Science World"],
    "22": ["Social Science American", "Social Science Anthropology", "Social Science Economics", "Social Science Linguistics", "Social Science Other", "Social Science Political Science", "Social Science Psychology", "Social Science Sociology"],
    "16": ["Trash American", "Trash Movies", "Trash Music", "Trash Other", "Trash Sports", "Trash Television", "Trash Video Games"]
}

const subIds = {
    "Current Events American": "40",
    "Current Events Other": "42",
    "Fine Arts American": "35",
    "Fine Arts Audiovisual": "27",
    "Fine Arts Auditory": "8",
    "Fine Arts British": "45",
    "Fine Arts European": "50",
    "Fine Arts Opera": "77",
    "Fine Arts Other": "25",
    "Fine Arts Visual": "2",
    "Fine Arts World": "43",
    "Geography American": "38",
    "Geography World": "44",
    "History American": "13",
    "History British": "6",
    "History Classical": "16",
    "History European": "24",
    "History Other": "28",
    "History World": "20",
    "Literature American": "4",
    "Literature British": "22",
    "Literature Classical": "30",
    "Literature European": "1",
    "Literature Other": "29",
    "Literature World": "12",
    "Mythology American": "33",
    "Mythology Chinese": "47",
    "Mythology Egyptian": "65",
    "Mythology Greco-Roman": "58",
    "Mythology Indian": "46",
    "Mythology Japanese": "48",
    "Mythology Norse": "63",
    "Mythology Other": "54",
    "Mythology Other East Asian": "49",
    "Philosophy American": "39",
    "Philosophy Classical": "61",
    "Philosophy East Asian": "52",
    "Philosophy European": "66",
    "Philosophy Other": "74",
    "Religion American": "31",
    "Religion Christianity": "57",
    "Religion East Asian": "51",
    "Religion Islam": "68",
    "Religion Judaism": "69",
    "Religion Other": "62",
    "Science American": "36",
    "Science Biology": "14",
    "Science Chemistry": "5",
    "Science Computer Science": "23",
    "Science Math": "26",
    "Science Other": "10",
    "Science Physics": "18",
    "Science World": "37",
    "Social Science American": "34",
    "Social Science Anthropology": "76",
    "Social Science Economics": "56",
    "Social Science Linguistics": "75",
    "Social Science Other": "60",
    "Social Science Political Science": "64",
    "Social Science Psychology": "71",
    "Social Science Sociology": "73",
    "Trash American": "32",
    "Trash Movies": "72",
    "Trash Music": "67",
    "Trash Other": "59",
    "Trash Sports": "55",
    "Trash Television": "70",
    "Trash Video Games": "53"
};